<#
.SYNOPSIS
Builds the stock production TIC-80 web package in a separate CMake tree.

.DESCRIPTION
Activate an Emscripten SDK environment, then run this script. output is
bin/index.html, bin/tic80.js, and bin/tic80.wasm below the build directory.
#>
[CmdletBinding()]
param(
    [string]$BuildDirectory
)

$ErrorActionPreference = 'Stop'

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))

# Upstream builds in the source-controlled build directory, which also contains
# web assets. Use a separate tree so configuring CMake cannot disturb those files.
if (-not $BuildDirectory) {
    $BuildDirectory = Join-Path $repoRoot 'out\emscripten'
} elseif (-not [System.IO.Path]::IsPathRooted($BuildDirectory)) {
    $BuildDirectory = Join-Path $repoRoot $BuildDirectory
}
$BuildDirectory = [System.IO.Path]::GetFullPath($BuildDirectory)

$emcmake = Get-Command emcmake -ErrorAction Stop
$cmake = Get-Command cmake -ErrorAction Stop
Get-Command ninja -ErrorAction Stop | Out-Null

# The production build enables Janet, whose amalgamated C source is generated by
# a native POSIX make process before Emscripten compiles it for the web target.
# On Windows, RubyInstaller already provides the required MSYS make and shell
# utilities, but does not put that directory on PATH by default. mingw32-make is
# deliberately insufficient because Janet's Makefile invokes `mkdir -p`.
$make = Get-Command make -ErrorAction SilentlyContinue
if (-not $make) {
    $ruby = Get-Command ruby -ErrorAction SilentlyContinue
    if ($ruby) {
        $rubyRoot = Split-Path -Parent (Split-Path -Parent $ruby.Source)
        $rubyMsysBin = Join-Path $rubyRoot 'msys64\usr\bin'
        $rubyMsysMake = Join-Path $rubyMsysBin 'make.exe'
        if (Test-Path -LiteralPath $rubyMsysMake -PathType Leaf) {
            $env:PATH = "$rubyMsysBin;$env:PATH"
            $make = Get-Command make -ErrorAction SilentlyContinue
        }
    }
}
if (-not $make) {
    throw 'The all-languages web build requires a POSIX make environment for Janet source generation.'
}

# Match the upstream "Build all" web job. --fresh makes the convenience command
# deterministic when the existing build tree was configured with other options.
$configureArgs = @(
    'cmake',
    '-S', $repoRoot,
    '-B', $BuildDirectory,
    '-G', 'Ninja',
    '-DBUILD_SDLGPU=On',
    '-DBUILD_STATIC=ON',
    '-DCMAKE_BUILD_TYPE=Release',
    '-DBUILD_WITH_ALL=ON',
    # some dependencies require this; make it explicit.
    '-DCMAKE_POLICY_VERSION_MINIMUM=3.5',
    '--fresh'
)

Write-Host "Configuring the production TIC-80 web build in $BuildDirectory"
& $emcmake.Source @configureArgs
if ($LASTEXITCODE -ne 0) {
    throw "Emscripten CMake configuration failed with exit code $LASTEXITCODE"
}

Write-Host 'Building the production TIC-80 web target'
& $cmake.Source --build $BuildDirectory --parallel
if ($LASTEXITCODE -ne 0) {
    throw "Emscripten build failed with exit code $LASTEXITCODE"
}

# This is the same packaging step as the upstream "Build all" web job.
$outputDirectory = Join-Path $BuildDirectory 'bin'
Copy-Item -LiteralPath (Join-Path $repoRoot 'build\html\index.html') `
    -Destination (Join-Path $outputDirectory 'index.html') -Force

Write-Host "Web build ready in $outputDirectory"
