<#
.SYNOPSIS
Builds a TIC-80 web package in a separate CMake tree.

.DESCRIPTION
Activate an Emscripten SDK environment, then run this script. Output is
bin/index.html, bin/tic80.js, and bin/tic80.wasm below the build directory.

The Stock profile matches the upstream all-languages production package. The
LuaPerformance profile retains the editors and SDL GPU renderer, but includes
only Lua, removes automatic Lua instruction profiling, and selects O3 with LTO.

.EXAMPLE
.\tools\build-web.ps1 -Profile Stock

.EXAMPLE
.\tools\build-web.ps1 -Profile LuaPerformance
#>
[CmdletBinding()]
param(
    [string]$BuildDirectory,

    [ValidateSet('Stock', 'LuaPerformance')]
    [string]$Profile = 'Stock'
)

$ErrorActionPreference = 'Stop'

$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))

# Upstream builds in the source-controlled build directory, which also contains
# web assets. Use a separate tree so configuring CMake cannot disturb those files.
if (-not $BuildDirectory) {
    $defaultBuildDirectory = if ($Profile -eq 'Stock') {
        'out\emscripten'
    } else {
        'out\emscripten-lua-performance'
    }
    $BuildDirectory = Join-Path $repoRoot $defaultBuildDirectory
} elseif (-not [System.IO.Path]::IsPathRooted($BuildDirectory)) {
    $BuildDirectory = Join-Path $repoRoot $BuildDirectory
}
$BuildDirectory = [System.IO.Path]::GetFullPath($BuildDirectory)

$emcmake = Get-Command emcmake -ErrorAction Stop
$cmake = Get-Command cmake -ErrorAction Stop
Get-Command ninja -ErrorAction Stop | Out-Null

# The Stock profile enables Janet, whose amalgamated C source is generated by a
# native POSIX make process before Emscripten compiles it for the web target.
if ($Profile -eq 'Stock') {
    # On Windows, RubyInstaller already provides the required MSYS make and shell
    # utilities, but does not put that directory on PATH by default.
    $make = Get-Command make -ErrorAction SilentlyContinue
    if (-not $make) {
        $ruby = Get-Command ruby -ErrorAction SilentlyContinue
        if ($ruby) {
            $rubyRoot = Split-Path -Parent (Split-Path -Parent $ruby.Source)
            $rubyMsysBin = Join-Path $rubyRoot 'msys64\usr\bin'
            $rubyMsysMake = Join-Path $rubyMsysBin 'make.exe'
            if (Test-Path -LiteralPath $rubyMsysMake -PathType Leaf) {
                $env:PATH = "$rubyMsysBin;$env:PATH"
                $make = Get-Command make -ErrorAction SilentlyContinue
            }
        }
    }
    if (-not $make) {
        throw 'The Stock web profile requires a POSIX make environment for Janet source generation.'
    }
}

$profileConfigureArgs = if ($Profile -eq 'Stock') {
    @(
        '-DBUILD_WITH_ALL=ON',
        '-DBUILD_EDITORS=ON',
        '-DBUILD_LUA_PERF=ON',
        '-DBUILD_OPTIMIZE_FOR_SPEED=OFF'
    )
} else {
    @(
        '-DBUILD_WITH_ALL=OFF',
        '-DBUILD_WITH_LUA=ON',
        '-DBUILD_EDITORS=ON',
        '-DBUILD_LUA_PERF=OFF',
        '-DBUILD_OPTIMIZE_FOR_SPEED=ON'
    )
}

# --fresh makes each profile deterministic even when reusing its build tree.
$configureArgs = @(
    'cmake',
    '-S', $repoRoot,
    '-B', $BuildDirectory,
    '-G', 'Ninja',
    '-DBUILD_SDLGPU=On',
    '-DBUILD_STATIC=ON',
    '-DCMAKE_BUILD_TYPE=Release'
) + $profileConfigureArgs + @(
    # Some dependencies require this; make it explicit.
    '-DCMAKE_POLICY_VERSION_MINIMUM=3.5',
    '--fresh'
)

Write-Host "Configuring the $Profile TIC-80 web profile in $BuildDirectory"
& $emcmake.Source @configureArgs
if ($LASTEXITCODE -ne 0) {
    throw "Emscripten CMake configuration failed with exit code $LASTEXITCODE"
}

Write-Host "Building the $Profile TIC-80 web target"
& $cmake.Source --build $BuildDirectory --parallel
if ($LASTEXITCODE -ne 0) {
    throw "Emscripten build failed with exit code $LASTEXITCODE"
}

# This is the same packaging step as the upstream "Build all" web job.
$outputDirectory = Join-Path $BuildDirectory 'bin'
Copy-Item -LiteralPath (Join-Path $repoRoot 'build\html\index.html') `
    -Destination (Join-Path $outputDirectory 'index.html') -Force

Write-Host "Web build ready in $outputDirectory"
