# 1.0.1
set(TICBUILD_VERSION_MAJOR 1)
set(TICBUILD_VERSION_MINOR 0)
set(TICBUILD_VERSION_PATCH 1)
set(TICBUILD_VERSION "${TICBUILD_VERSION_MAJOR}.${TICBUILD_VERSION_MINOR}.${TICBUILD_VERSION_PATCH}")
